//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Entidades;
    
    public partial class PFinalEntities : DbContext
    {
        public PFinalEntities()
            : base("name=PFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Cuenta> Cuentas { get; set; }
        public virtual DbSet<Estado> Estadoes { get; set; }
        public virtual DbSet<Modulo> Moduloes { get; set; }
        public virtual DbSet<Operacione> Operaciones { get; set; }
        public virtual DbSet<Prestamo> Prestamoes { get; set; }
        public virtual DbSet<Retiro> Retiroes { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<RolOperacion> RolOperacions { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<TarjetaCredito> TarjetaCreditoes { get; set; }
    
        public virtual int SP_Deposito(Nullable<int> idC, Nullable<int> numC, Nullable<decimal> cantidad, Nullable<System.DateTime> fechaR, string accion)
        {
            var idCParameter = idC.HasValue ?
                new ObjectParameter("IdC", idC) :
                new ObjectParameter("IdC", typeof(int));
    
            var numCParameter = numC.HasValue ?
                new ObjectParameter("NumC", numC) :
                new ObjectParameter("NumC", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(decimal));
    
            var fechaRParameter = fechaR.HasValue ?
                new ObjectParameter("FechaR", fechaR) :
                new ObjectParameter("FechaR", typeof(System.DateTime));
    
            var accionParameter = accion != null ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Deposito", idCParameter, numCParameter, cantidadParameter, fechaRParameter, accionParameter);
        }
    
        public virtual int SP_Retiro(Nullable<int> idC, Nullable<int> numC, Nullable<decimal> cantidad, Nullable<System.DateTime> fechaR, string accion)
        {
            var idCParameter = idC.HasValue ?
                new ObjectParameter("IdC", idC) :
                new ObjectParameter("IdC", typeof(int));
    
            var numCParameter = numC.HasValue ?
                new ObjectParameter("NumC", numC) :
                new ObjectParameter("NumC", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(decimal));
    
            var fechaRParameter = fechaR.HasValue ?
                new ObjectParameter("FechaR", fechaR) :
                new ObjectParameter("FechaR", typeof(System.DateTime));
    
            var accionParameter = accion != null ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Retiro", idCParameter, numCParameter, cantidadParameter, fechaRParameter, accionParameter);
        }
    
        public virtual ObjectResult<SP_BucarRD_Result> SP_BucarRD(string accion, string numC, Nullable<System.DateTime> fECHA1, Nullable<System.DateTime> fECHA2)
        {
            var accionParameter = accion != null ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(string));
    
            var numCParameter = numC != null ?
                new ObjectParameter("NumC", numC) :
                new ObjectParameter("NumC", typeof(string));
    
            var fECHA1Parameter = fECHA1.HasValue ?
                new ObjectParameter("FECHA1", fECHA1) :
                new ObjectParameter("FECHA1", typeof(System.DateTime));
    
            var fECHA2Parameter = fECHA2.HasValue ?
                new ObjectParameter("FECHA2", fECHA2) :
                new ObjectParameter("FECHA2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BucarRD_Result>("SP_BucarRD", accionParameter, numCParameter, fECHA1Parameter, fECHA2Parameter);
        }
    }
}
